export const apiEndPoints = {
  getUser: `/todos`,
  product: '/products',
  signin: '/auth/signin',
  auth: '/auth',
  user: '/user',
  manufacturer: '/manufacturers/create',
  manufacturerList: '/manufacturers',
  orderEnum: '/admin/order/enums',
  category: '/category',
  brands: '/brands',
  media: '/media',
  tags: '/tags',
  ordersList: '/admin/order/orderList',
  singleOrder: '/admin/order',
};
