import {
  checkoutRest,
  addToWishlistRest,
  deleteFullWishlistRest,
  deleteWishlistItemRest,
  addToCompareRest,
  deleteFromCompareRest,
  forgotPasswordRest,
  getCustomerWishlistRest,
  getFeaturedProductsRest,
  getOrderProductsRest,
  getPublicProductByIdRest,
  getPublicProductByCategoryIDRest,
  getPublicProductsRest,
  getSignedInUserRest,
  signinRest,
  signUpRest,
  getCategoryListRest,
  getOrderProductRest,
  getCustomerProfileRest,
  deleteCustomerAddressRest,
  updateCustomerAddressRest,
  addCustomerNewAddressRest,
  getCustomerRest,
  updateCustomerRest,
  getCartRest,
  addToCartRest,
  deleteAllCartItemRest,
  deleteSingleCartItemRest,
  updateCartItemRest,
  sendOTPRest,
} from './restApi';

import {
  addToWishlistGraphql,
  deleteFullWishlistGraphql,
  deleteWishlistItemGraphql,
  addToCompareGraphql,
  deleteFromCompareGraphql,
  forgotPasswordGraphql,
  getCustomerWishlistGraphql,
  getFeaturedProductsGraphql,
  getPublicProductByIdGraphql,
  getPublicProductsGraphql,
  getSignedInUserGraphql,
  getPublicProductByCategoryIDGraphql,
  signInGraphql,
  signUpGraphql,
  getCategoryListGraphql,
  getCustomerProfileGraphql,
  deleteCustomerAddressGraphql,
  updateCustomerAddressGraphql,
  addCustomerNewAddressGraphql,
  checkoutGraphql,
  getCustomerGraphql,
  updateCustomerGraphql,
  getOrderProductsGraphql,
  getOrderProductGraphql,
  getCartGraphql,
  addToCartGraphql,
  deleteAllCartItemGraphql,
  deleteSingleCartItemGraphql,
  updateCartItemGraphql,
  sendOTPGraphql,
} from './graphQL';
import { config } from 'config';
import { apiFunction } from 'utils/types';

const graphqlApi: apiFunction = {
  signIn: signInGraphql,
  sendOTP: sendOTPGraphql,
  signUp: signUpGraphql,
  getSignedInUser: getSignedInUserGraphql,
  forgotPassword: forgotPasswordGraphql,
  getPublicProducts: getPublicProductsGraphql,
  getPublicProductsById: getPublicProductByIdGraphql,
  getPublicProductByCategoryId: getPublicProductByCategoryIDGraphql,
  getFeaturedProducts: getFeaturedProductsGraphql,
  getCategoryList: getCategoryListGraphql,
  checkout: checkoutGraphql,
  getOrderProducts: getOrderProductsGraphql,
  getOrderProduct: getOrderProductGraphql,
  addToWishList: addToWishlistGraphql,
  getCustomerWishlist: getCustomerWishlistGraphql,
  deleteWishlistItem: deleteWishlistItemGraphql,
  deleteFullWishlist: deleteFullWishlistGraphql,
  addToCompare: addToCompareGraphql,
  deleteFromCompare: deleteFromCompareGraphql,
  getCustomerProfile: getCustomerProfileGraphql,
  deleteCustomerAddress: deleteCustomerAddressGraphql,
  updateCustomerAddress: updateCustomerAddressGraphql,
  addCustomerNewAddress: addCustomerNewAddressGraphql,
  getCustomer: getCustomerGraphql,
  updateCustomer: updateCustomerGraphql,
  getCart: getCartGraphql,
  addToCart: addToCartGraphql,
  deleteAllCartItem: deleteAllCartItemGraphql,
  deleteSingleCartItem: deleteSingleCartItemGraphql,
  updateCartItem: updateCartItemGraphql,
};

const restApi: apiFunction = {
  signUp: signUpRest,
  sendOTP: sendOTPRest,
  signIn: signinRest,
  getSignedInUser: getSignedInUserRest,
  forgotPassword: forgotPasswordRest,
  getPublicProducts: getPublicProductsRest,
  getPublicProductsById: getPublicProductByIdRest,
  getPublicProductByCategoryId: getPublicProductByCategoryIDRest,
  getFeaturedProducts: getFeaturedProductsRest,
  getCategoryList: getCategoryListRest,
  checkout: checkoutRest,
  getOrderProducts: getOrderProductsRest,
  getOrderProduct: getOrderProductRest,
  addToWishList: addToWishlistRest,
  getCustomerWishlist: getCustomerWishlistRest,
  deleteWishlistItem: deleteWishlistItemRest,
  deleteFullWishlist: deleteFullWishlistRest,
  addToCompare: addToCompareRest,
  deleteFromCompare: deleteFromCompareRest,
  getCustomerProfile: getCustomerProfileRest,
  deleteCustomerAddress: deleteCustomerAddressRest,
  updateCustomerAddress: updateCustomerAddressRest,
  addCustomerNewAddress: addCustomerNewAddressRest,
  getCustomer: getCustomerRest,
  updateCustomer: updateCustomerRest,
  getCart: getCartRest,
  addToCart: addToCartRest,
  deleteAllCartItem: deleteAllCartItemRest,
  deleteSingleCartItem: deleteSingleCartItemRest,
  updateCartItem: updateCartItemRest,
};

export const userAPI: apiFunction =
  config?.apiService === 'GRAPHQL' ? graphqlApi : restApi;
