export const enum ErrorMessageReOrder{
    CANNOT_CREATE_CART = 'CANNOT CREATE CART',
    INVALID_ID = 'INVALID ID',
    OVERWRITE_CART = 'YOUR ITEMS IN THE CART WILL BE REPLACED. DO YOU WANT TO CONTINUE?',
    INVALID_ITEMS = 'SOME PRODUCTS ARE NOT AVAILABLE. DO YOU WISH TO CONTINUE?',
    CANNOT_CLEAR_CART = 'CANNOT CLEAR THE EXISTING ITEMS IN YOUR CART',
    ALL_ITEMS_INVALID = 'THESE ITEMS ARE NOT AVAILABLE RIGHT NOW',
    CANNOT_ADD_ITEMS = 'CANNOT ADD ITEMS TO THE CART'
}