import {
  getProductsRest,
  getProductSearchRest,
  createProductRest,
  getProductRest,
  updateProductRest,
  deleteProductRest,
  signinRest,
  createAdminRest,
  getAdminsRest,
  updateAdminRest,
  changePasswordRest,
  createManufacturerRest,
  getManufacturerRest,
  deleteManufacturerRest,
  getSingleManufacturerRest,
  updateManufacturerRest,
  getUserProfileRest,
  getCategoryListRest,
  getCategoryRest,
  getBrandsRest,
  getBrandRest,
  createCategoryRest,
  mediaUploadRest,
  getTagsRest,
  getAllManufacturersRest,
  createBrandRest,
  getOrderEnumRest,
  getAllOrderListRest,
  getSingleOrderByIdRest,
  getOrderListRest,
  getOrderRest,
  updateOrderStatusRest,
  updatePaymentStatusRest,
  updateShippingStatusRest,
  deleteBrandRest,
  updateBrandRest,
  getAllTagsRest,
  createTagsRest,
  getSingleTagRest,
} from './restApi';
import {
  getProductsGraphQL,
  getProductSearchGraphQL,
  signinGraphQL,
  createAdminGraphql,
  getAdminsGraphql,
  updateAdminGraphql,
  changePasswordGraphql,
  getUserProfileGraphql,
  getCategoryListGraphQL,
  getCategoryGraphQL,
  getBrandsGraphQL,
  getBrandGraphQL,
  createCategoryGraphQL,
  mediaUploadGraphQL,
  getTagsGraphQL,
  createBrandGraphQL,
  // getManufacturerGraphQl,
  // deleteManufacturerGraphQl,
  // createManufacturerGraphQl,
  getAllOrderListGraphQL,
  deleteBrandGraphQL,
  updateBrandGraphQL,
} from './graphQL';
import { config } from '../config/index';
import { apiFunction } from '../utils/types';

const graphqlApi: apiFunction = {
  getProducts: getProductsGraphQL,
  searchProduct: getProductSearchGraphQL,
  getCategoryList: getCategoryListGraphQL,
  getCategory: getCategoryGraphQL,
  createCategory: createCategoryGraphQL,
  createProduct: createProductRest,
  updateProduct: updateProductRest,
  getProduct: getProductRest,
  deleteProduct: deleteProductRest,
  signin: signinGraphQL,
  createAdmin: createAdminGraphql,
  getAdmins: getAdminsGraphql,
  updateAdmin: updateAdminGraphql,
  changePassword: changePasswordGraphql,
  getUserProfile: getUserProfileGraphql,
  // getManufacturer: getManufacturerGraphQl,
  // deleteManufacturer: deleteManufacturerGraphQl,
  // createManufacturer: createManufacturerGraphQl
  getBrands: getBrandsGraphQL,
  getBrand: getBrandGraphQL,
  mediaUpload: mediaUploadGraphQL,
  getTags: getTagsGraphQL,
  createBrand: createBrandGraphQL,
  getAllOrderList: getAllOrderListGraphQL,
  deleteBrand: deleteBrandGraphQL,
  updateBrand: updateBrandGraphQL,
};

const restApi: apiFunction = {
  getProducts: getProductsRest,
  searchProduct: getProductSearchRest,
  getCategoryList: getCategoryListRest,
  getCategory: getCategoryRest,
  createCategory: createCategoryRest,
  createProduct: createProductRest,
  updateProduct: updateProductRest,
  getProduct: getProductRest,
  deleteProduct: deleteProductRest,
  signin: signinRest,
  createAdmin: createAdminRest,
  getAdmins: getAdminsRest,
  updateAdmin: updateAdminRest,
  changePassword: changePasswordRest,
  createManufacturer: createManufacturerRest,
  getManufacturer: getManufacturerRest,
  deleteManufacturer: deleteManufacturerRest,
  getSingleManufacturer: getSingleManufacturerRest,
  updateManufacturer: updateManufacturerRest,
  getOrderEnum: getOrderEnumRest,
  updateOrderStatus: updateOrderStatusRest,
  updatePaymentStatus: updatePaymentStatusRest,
  updateShippingStatus: updateShippingStatusRest,
  getUserProfile: getUserProfileRest,
  getBrands: getBrandsRest,
  getBrand: getBrandRest,
  mediaUpload: mediaUploadRest,
  getTags: getTagsRest,
  getAllManufacturers: getAllManufacturersRest,
  createBrand: createBrandRest,
  getAllOrderList: getAllOrderListRest,
  getSingleOrderById: getSingleOrderByIdRest,
  deleteBrand: deleteBrandRest,
  updateBrand: updateBrandRest,
  getAllTags: getAllTagsRest,
  createTags: createTagsRest,
  getSingleTag: getSingleTagRest,
};

export const userAPI: apiFunction =
  config?.apiService === 'GRAPHQL' ? graphqlApi : restApi;
