version: '3.6'
services:
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.0
    volumes:
      - bscom-esdata:/usr/share/elasticsearch/data
    environment:
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
    logging:
      driver: none
    ports:
      - 9300:9300
      - 9200:9200

  mongodb_container:
    image: mongo:latest
    ports:
      - 27018:27017
    volumes:
      - bscom-mongodb:/usr/share/mongo/data

volumes:
  bscom-esdata:
  bscom-mongodb: